"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___ProtoOAPayloadType = ProtoOAPayloadType
class _ProtoOAPayloadType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAPayloadType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    PROTO_OA_APPLICATION_AUTH_REQ = ProtoOAPayloadType.V(2100)
    PROTO_OA_APPLICATION_AUTH_RES = ProtoOAPayloadType.V(2101)
    PROTO_OA_ACCOUNT_AUTH_REQ = ProtoOAPayloadType.V(2102)
    PROTO_OA_ACCOUNT_AUTH_RES = ProtoOAPayloadType.V(2103)
    PROTO_OA_VERSION_REQ = ProtoOAPayloadType.V(2104)
    PROTO_OA_VERSION_RES = ProtoOAPayloadType.V(2105)
    PROTO_OA_NEW_ORDER_REQ = ProtoOAPayloadType.V(2106)
    PROTO_OA_TRAILING_SL_CHANGED_EVENT = ProtoOAPayloadType.V(2107)
    PROTO_OA_CANCEL_ORDER_REQ = ProtoOAPayloadType.V(2108)
    PROTO_OA_AMEND_ORDER_REQ = ProtoOAPayloadType.V(2109)
    PROTO_OA_AMEND_POSITION_SLTP_REQ = ProtoOAPayloadType.V(2110)
    PROTO_OA_CLOSE_POSITION_REQ = ProtoOAPayloadType.V(2111)
    PROTO_OA_ASSET_LIST_REQ = ProtoOAPayloadType.V(2112)
    PROTO_OA_ASSET_LIST_RES = ProtoOAPayloadType.V(2113)
    PROTO_OA_SYMBOLS_LIST_REQ = ProtoOAPayloadType.V(2114)
    PROTO_OA_SYMBOLS_LIST_RES = ProtoOAPayloadType.V(2115)
    PROTO_OA_SYMBOL_BY_ID_REQ = ProtoOAPayloadType.V(2116)
    PROTO_OA_SYMBOL_BY_ID_RES = ProtoOAPayloadType.V(2117)
    PROTO_OA_SYMBOLS_FOR_CONVERSION_REQ = ProtoOAPayloadType.V(2118)
    PROTO_OA_SYMBOLS_FOR_CONVERSION_RES = ProtoOAPayloadType.V(2119)
    PROTO_OA_SYMBOL_CHANGED_EVENT = ProtoOAPayloadType.V(2120)
    PROTO_OA_TRADER_REQ = ProtoOAPayloadType.V(2121)
    PROTO_OA_TRADER_RES = ProtoOAPayloadType.V(2122)
    PROTO_OA_TRADER_UPDATE_EVENT = ProtoOAPayloadType.V(2123)
    PROTO_OA_RECONCILE_REQ = ProtoOAPayloadType.V(2124)
    PROTO_OA_RECONCILE_RES = ProtoOAPayloadType.V(2125)
    PROTO_OA_EXECUTION_EVENT = ProtoOAPayloadType.V(2126)
    PROTO_OA_SUBSCRIBE_SPOTS_REQ = ProtoOAPayloadType.V(2127)
    PROTO_OA_SUBSCRIBE_SPOTS_RES = ProtoOAPayloadType.V(2128)
    PROTO_OA_UNSUBSCRIBE_SPOTS_REQ = ProtoOAPayloadType.V(2129)
    PROTO_OA_UNSUBSCRIBE_SPOTS_RES = ProtoOAPayloadType.V(2130)
    PROTO_OA_SPOT_EVENT = ProtoOAPayloadType.V(2131)
    PROTO_OA_ORDER_ERROR_EVENT = ProtoOAPayloadType.V(2132)
    PROTO_OA_DEAL_LIST_REQ = ProtoOAPayloadType.V(2133)
    PROTO_OA_DEAL_LIST_RES = ProtoOAPayloadType.V(2134)
    PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ = ProtoOAPayloadType.V(2135)
    PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_REQ = ProtoOAPayloadType.V(2136)
    PROTO_OA_GET_TRENDBARS_REQ = ProtoOAPayloadType.V(2137)
    PROTO_OA_GET_TRENDBARS_RES = ProtoOAPayloadType.V(2138)
    PROTO_OA_EXPECTED_MARGIN_REQ = ProtoOAPayloadType.V(2139)
    PROTO_OA_EXPECTED_MARGIN_RES = ProtoOAPayloadType.V(2140)
    PROTO_OA_MARGIN_CHANGED_EVENT = ProtoOAPayloadType.V(2141)
    PROTO_OA_ERROR_RES = ProtoOAPayloadType.V(2142)
    PROTO_OA_CASH_FLOW_HISTORY_LIST_REQ = ProtoOAPayloadType.V(2143)
    PROTO_OA_CASH_FLOW_HISTORY_LIST_RES = ProtoOAPayloadType.V(2144)
    PROTO_OA_GET_TICKDATA_REQ = ProtoOAPayloadType.V(2145)
    PROTO_OA_GET_TICKDATA_RES = ProtoOAPayloadType.V(2146)
    PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED_EVENT = ProtoOAPayloadType.V(2147)
    PROTO_OA_CLIENT_DISCONNECT_EVENT = ProtoOAPayloadType.V(2148)
    PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ = ProtoOAPayloadType.V(2149)
    PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES = ProtoOAPayloadType.V(2150)
    PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_REQ = ProtoOAPayloadType.V(2151)
    PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_RES = ProtoOAPayloadType.V(2152)
    PROTO_OA_ASSET_CLASS_LIST_REQ = ProtoOAPayloadType.V(2153)
    PROTO_OA_ASSET_CLASS_LIST_RES = ProtoOAPayloadType.V(2154)
    PROTO_OA_DEPTH_EVENT = ProtoOAPayloadType.V(2155)
    PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_REQ = ProtoOAPayloadType.V(2156)
    PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_RES = ProtoOAPayloadType.V(2157)
    PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_REQ = ProtoOAPayloadType.V(2158)
    PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_RES = ProtoOAPayloadType.V(2159)
    PROTO_OA_SYMBOL_CATEGORY_REQ = ProtoOAPayloadType.V(2160)
    PROTO_OA_SYMBOL_CATEGORY_RES = ProtoOAPayloadType.V(2161)
    PROTO_OA_ACCOUNT_LOGOUT_REQ = ProtoOAPayloadType.V(2162)
    PROTO_OA_ACCOUNT_LOGOUT_RES = ProtoOAPayloadType.V(2163)
    PROTO_OA_ACCOUNT_DISCONNECT_EVENT = ProtoOAPayloadType.V(2164)
    PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_RES = ProtoOAPayloadType.V(2165)
    PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_RES = ProtoOAPayloadType.V(2166)
    PROTO_OA_MARGIN_CALL_LIST_REQ = ProtoOAPayloadType.V(2167)
    PROTO_OA_MARGIN_CALL_LIST_RES = ProtoOAPayloadType.V(2168)
    PROTO_OA_MARGIN_CALL_UPDATE_REQ = ProtoOAPayloadType.V(2169)
    PROTO_OA_MARGIN_CALL_UPDATE_RES = ProtoOAPayloadType.V(2170)
    PROTO_OA_MARGIN_CALL_UPDATE_EVENT = ProtoOAPayloadType.V(2171)
    PROTO_OA_MARGIN_CALL_TRIGGER_EVENT = ProtoOAPayloadType.V(2172)
    PROTO_OA_REFRESH_TOKEN_REQ = ProtoOAPayloadType.V(2173)
    PROTO_OA_REFRESH_TOKEN_RES = ProtoOAPayloadType.V(2174)
class ProtoOAPayloadType(metaclass=_ProtoOAPayloadType):
    V = typing.NewType('V', builtins.int)
PROTO_OA_APPLICATION_AUTH_REQ = ProtoOAPayloadType.V(2100)
PROTO_OA_APPLICATION_AUTH_RES = ProtoOAPayloadType.V(2101)
PROTO_OA_ACCOUNT_AUTH_REQ = ProtoOAPayloadType.V(2102)
PROTO_OA_ACCOUNT_AUTH_RES = ProtoOAPayloadType.V(2103)
PROTO_OA_VERSION_REQ = ProtoOAPayloadType.V(2104)
PROTO_OA_VERSION_RES = ProtoOAPayloadType.V(2105)
PROTO_OA_NEW_ORDER_REQ = ProtoOAPayloadType.V(2106)
PROTO_OA_TRAILING_SL_CHANGED_EVENT = ProtoOAPayloadType.V(2107)
PROTO_OA_CANCEL_ORDER_REQ = ProtoOAPayloadType.V(2108)
PROTO_OA_AMEND_ORDER_REQ = ProtoOAPayloadType.V(2109)
PROTO_OA_AMEND_POSITION_SLTP_REQ = ProtoOAPayloadType.V(2110)
PROTO_OA_CLOSE_POSITION_REQ = ProtoOAPayloadType.V(2111)
PROTO_OA_ASSET_LIST_REQ = ProtoOAPayloadType.V(2112)
PROTO_OA_ASSET_LIST_RES = ProtoOAPayloadType.V(2113)
PROTO_OA_SYMBOLS_LIST_REQ = ProtoOAPayloadType.V(2114)
PROTO_OA_SYMBOLS_LIST_RES = ProtoOAPayloadType.V(2115)
PROTO_OA_SYMBOL_BY_ID_REQ = ProtoOAPayloadType.V(2116)
PROTO_OA_SYMBOL_BY_ID_RES = ProtoOAPayloadType.V(2117)
PROTO_OA_SYMBOLS_FOR_CONVERSION_REQ = ProtoOAPayloadType.V(2118)
PROTO_OA_SYMBOLS_FOR_CONVERSION_RES = ProtoOAPayloadType.V(2119)
PROTO_OA_SYMBOL_CHANGED_EVENT = ProtoOAPayloadType.V(2120)
PROTO_OA_TRADER_REQ = ProtoOAPayloadType.V(2121)
PROTO_OA_TRADER_RES = ProtoOAPayloadType.V(2122)
PROTO_OA_TRADER_UPDATE_EVENT = ProtoOAPayloadType.V(2123)
PROTO_OA_RECONCILE_REQ = ProtoOAPayloadType.V(2124)
PROTO_OA_RECONCILE_RES = ProtoOAPayloadType.V(2125)
PROTO_OA_EXECUTION_EVENT = ProtoOAPayloadType.V(2126)
PROTO_OA_SUBSCRIBE_SPOTS_REQ = ProtoOAPayloadType.V(2127)
PROTO_OA_SUBSCRIBE_SPOTS_RES = ProtoOAPayloadType.V(2128)
PROTO_OA_UNSUBSCRIBE_SPOTS_REQ = ProtoOAPayloadType.V(2129)
PROTO_OA_UNSUBSCRIBE_SPOTS_RES = ProtoOAPayloadType.V(2130)
PROTO_OA_SPOT_EVENT = ProtoOAPayloadType.V(2131)
PROTO_OA_ORDER_ERROR_EVENT = ProtoOAPayloadType.V(2132)
PROTO_OA_DEAL_LIST_REQ = ProtoOAPayloadType.V(2133)
PROTO_OA_DEAL_LIST_RES = ProtoOAPayloadType.V(2134)
PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ = ProtoOAPayloadType.V(2135)
PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_REQ = ProtoOAPayloadType.V(2136)
PROTO_OA_GET_TRENDBARS_REQ = ProtoOAPayloadType.V(2137)
PROTO_OA_GET_TRENDBARS_RES = ProtoOAPayloadType.V(2138)
PROTO_OA_EXPECTED_MARGIN_REQ = ProtoOAPayloadType.V(2139)
PROTO_OA_EXPECTED_MARGIN_RES = ProtoOAPayloadType.V(2140)
PROTO_OA_MARGIN_CHANGED_EVENT = ProtoOAPayloadType.V(2141)
PROTO_OA_ERROR_RES = ProtoOAPayloadType.V(2142)
PROTO_OA_CASH_FLOW_HISTORY_LIST_REQ = ProtoOAPayloadType.V(2143)
PROTO_OA_CASH_FLOW_HISTORY_LIST_RES = ProtoOAPayloadType.V(2144)
PROTO_OA_GET_TICKDATA_REQ = ProtoOAPayloadType.V(2145)
PROTO_OA_GET_TICKDATA_RES = ProtoOAPayloadType.V(2146)
PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED_EVENT = ProtoOAPayloadType.V(2147)
PROTO_OA_CLIENT_DISCONNECT_EVENT = ProtoOAPayloadType.V(2148)
PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ = ProtoOAPayloadType.V(2149)
PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES = ProtoOAPayloadType.V(2150)
PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_REQ = ProtoOAPayloadType.V(2151)
PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_RES = ProtoOAPayloadType.V(2152)
PROTO_OA_ASSET_CLASS_LIST_REQ = ProtoOAPayloadType.V(2153)
PROTO_OA_ASSET_CLASS_LIST_RES = ProtoOAPayloadType.V(2154)
PROTO_OA_DEPTH_EVENT = ProtoOAPayloadType.V(2155)
PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_REQ = ProtoOAPayloadType.V(2156)
PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_RES = ProtoOAPayloadType.V(2157)
PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_REQ = ProtoOAPayloadType.V(2158)
PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_RES = ProtoOAPayloadType.V(2159)
PROTO_OA_SYMBOL_CATEGORY_REQ = ProtoOAPayloadType.V(2160)
PROTO_OA_SYMBOL_CATEGORY_RES = ProtoOAPayloadType.V(2161)
PROTO_OA_ACCOUNT_LOGOUT_REQ = ProtoOAPayloadType.V(2162)
PROTO_OA_ACCOUNT_LOGOUT_RES = ProtoOAPayloadType.V(2163)
PROTO_OA_ACCOUNT_DISCONNECT_EVENT = ProtoOAPayloadType.V(2164)
PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_RES = ProtoOAPayloadType.V(2165)
PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_RES = ProtoOAPayloadType.V(2166)
PROTO_OA_MARGIN_CALL_LIST_REQ = ProtoOAPayloadType.V(2167)
PROTO_OA_MARGIN_CALL_LIST_RES = ProtoOAPayloadType.V(2168)
PROTO_OA_MARGIN_CALL_UPDATE_REQ = ProtoOAPayloadType.V(2169)
PROTO_OA_MARGIN_CALL_UPDATE_RES = ProtoOAPayloadType.V(2170)
PROTO_OA_MARGIN_CALL_UPDATE_EVENT = ProtoOAPayloadType.V(2171)
PROTO_OA_MARGIN_CALL_TRIGGER_EVENT = ProtoOAPayloadType.V(2172)
PROTO_OA_REFRESH_TOKEN_REQ = ProtoOAPayloadType.V(2173)
PROTO_OA_REFRESH_TOKEN_RES = ProtoOAPayloadType.V(2174)

global___ProtoOADayOfWeek = ProtoOADayOfWeek
class _ProtoOADayOfWeek(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOADayOfWeek.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NONE = ProtoOADayOfWeek.V(0)
    MONDAY = ProtoOADayOfWeek.V(1)
    TUESDAY = ProtoOADayOfWeek.V(2)
    WEDNESDAY = ProtoOADayOfWeek.V(3)
    THURSDAY = ProtoOADayOfWeek.V(4)
    FRIDAY = ProtoOADayOfWeek.V(5)
    SATURDAY = ProtoOADayOfWeek.V(6)
    SUNDAY = ProtoOADayOfWeek.V(7)
class ProtoOADayOfWeek(metaclass=_ProtoOADayOfWeek):
    V = typing.NewType('V', builtins.int)
NONE = ProtoOADayOfWeek.V(0)
MONDAY = ProtoOADayOfWeek.V(1)
TUESDAY = ProtoOADayOfWeek.V(2)
WEDNESDAY = ProtoOADayOfWeek.V(3)
THURSDAY = ProtoOADayOfWeek.V(4)
FRIDAY = ProtoOADayOfWeek.V(5)
SATURDAY = ProtoOADayOfWeek.V(6)
SUNDAY = ProtoOADayOfWeek.V(7)

global___ProtoOACommissionType = ProtoOACommissionType
class _ProtoOACommissionType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOACommissionType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    USD_PER_MILLION_USD = ProtoOACommissionType.V(1)
    USD_PER_LOT = ProtoOACommissionType.V(2)
    PERCENTAGE_OF_VALUE = ProtoOACommissionType.V(3)
    QUOTE_CCY_PER_LOT = ProtoOACommissionType.V(4)
class ProtoOACommissionType(metaclass=_ProtoOACommissionType):
    V = typing.NewType('V', builtins.int)
USD_PER_MILLION_USD = ProtoOACommissionType.V(1)
USD_PER_LOT = ProtoOACommissionType.V(2)
PERCENTAGE_OF_VALUE = ProtoOACommissionType.V(3)
QUOTE_CCY_PER_LOT = ProtoOACommissionType.V(4)

global___ProtoOASymbolDistanceType = ProtoOASymbolDistanceType
class _ProtoOASymbolDistanceType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOASymbolDistanceType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    SYMBOL_DISTANCE_IN_POINTS = ProtoOASymbolDistanceType.V(1)
    SYMBOL_DISTANCE_IN_PERCENTAGE = ProtoOASymbolDistanceType.V(2)
class ProtoOASymbolDistanceType(metaclass=_ProtoOASymbolDistanceType):
    V = typing.NewType('V', builtins.int)
SYMBOL_DISTANCE_IN_POINTS = ProtoOASymbolDistanceType.V(1)
SYMBOL_DISTANCE_IN_PERCENTAGE = ProtoOASymbolDistanceType.V(2)

global___ProtoOAMinCommissionType = ProtoOAMinCommissionType
class _ProtoOAMinCommissionType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAMinCommissionType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CURRENCY = ProtoOAMinCommissionType.V(1)
    QUOTE_CURRENCY = ProtoOAMinCommissionType.V(2)
class ProtoOAMinCommissionType(metaclass=_ProtoOAMinCommissionType):
    V = typing.NewType('V', builtins.int)
CURRENCY = ProtoOAMinCommissionType.V(1)
QUOTE_CURRENCY = ProtoOAMinCommissionType.V(2)

global___ProtoOATradingMode = ProtoOATradingMode
class _ProtoOATradingMode(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOATradingMode.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ENABLED = ProtoOATradingMode.V(0)
    DISABLED_WITHOUT_PENDINGS_EXECUTION = ProtoOATradingMode.V(1)
    DISABLED_WITH_PENDINGS_EXECUTION = ProtoOATradingMode.V(2)
    CLOSE_ONLY_MODE = ProtoOATradingMode.V(3)
class ProtoOATradingMode(metaclass=_ProtoOATradingMode):
    V = typing.NewType('V', builtins.int)
ENABLED = ProtoOATradingMode.V(0)
DISABLED_WITHOUT_PENDINGS_EXECUTION = ProtoOATradingMode.V(1)
DISABLED_WITH_PENDINGS_EXECUTION = ProtoOATradingMode.V(2)
CLOSE_ONLY_MODE = ProtoOATradingMode.V(3)

global___ProtoOASwapCalculationType = ProtoOASwapCalculationType
class _ProtoOASwapCalculationType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOASwapCalculationType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    PIPS = ProtoOASwapCalculationType.V(0)
    PERCENTAGE = ProtoOASwapCalculationType.V(1)
class ProtoOASwapCalculationType(metaclass=_ProtoOASwapCalculationType):
    V = typing.NewType('V', builtins.int)
PIPS = ProtoOASwapCalculationType.V(0)
PERCENTAGE = ProtoOASwapCalculationType.V(1)

global___ProtoOAAccessRights = ProtoOAAccessRights
class _ProtoOAAccessRights(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAAccessRights.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    FULL_ACCESS = ProtoOAAccessRights.V(0)
    CLOSE_ONLY = ProtoOAAccessRights.V(1)
    NO_TRADING = ProtoOAAccessRights.V(2)
    NO_LOGIN = ProtoOAAccessRights.V(3)
class ProtoOAAccessRights(metaclass=_ProtoOAAccessRights):
    V = typing.NewType('V', builtins.int)
FULL_ACCESS = ProtoOAAccessRights.V(0)
CLOSE_ONLY = ProtoOAAccessRights.V(1)
NO_TRADING = ProtoOAAccessRights.V(2)
NO_LOGIN = ProtoOAAccessRights.V(3)

global___ProtoOATotalMarginCalculationType = ProtoOATotalMarginCalculationType
class _ProtoOATotalMarginCalculationType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOATotalMarginCalculationType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    MAX = ProtoOATotalMarginCalculationType.V(0)
    SUM = ProtoOATotalMarginCalculationType.V(1)
    NET = ProtoOATotalMarginCalculationType.V(2)
class ProtoOATotalMarginCalculationType(metaclass=_ProtoOATotalMarginCalculationType):
    V = typing.NewType('V', builtins.int)
MAX = ProtoOATotalMarginCalculationType.V(0)
SUM = ProtoOATotalMarginCalculationType.V(1)
NET = ProtoOATotalMarginCalculationType.V(2)

global___ProtoOAAccountType = ProtoOAAccountType
class _ProtoOAAccountType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAAccountType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    HEDGED = ProtoOAAccountType.V(0)
    NETTED = ProtoOAAccountType.V(1)
    SPREAD_BETTING = ProtoOAAccountType.V(2)
class ProtoOAAccountType(metaclass=_ProtoOAAccountType):
    V = typing.NewType('V', builtins.int)
HEDGED = ProtoOAAccountType.V(0)
NETTED = ProtoOAAccountType.V(1)
SPREAD_BETTING = ProtoOAAccountType.V(2)

global___ProtoOAPositionStatus = ProtoOAPositionStatus
class _ProtoOAPositionStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAPositionStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    POSITION_STATUS_OPEN = ProtoOAPositionStatus.V(1)
    POSITION_STATUS_CLOSED = ProtoOAPositionStatus.V(2)
    POSITION_STATUS_CREATED = ProtoOAPositionStatus.V(3)
    POSITION_STATUS_ERROR = ProtoOAPositionStatus.V(4)
class ProtoOAPositionStatus(metaclass=_ProtoOAPositionStatus):
    V = typing.NewType('V', builtins.int)
POSITION_STATUS_OPEN = ProtoOAPositionStatus.V(1)
POSITION_STATUS_CLOSED = ProtoOAPositionStatus.V(2)
POSITION_STATUS_CREATED = ProtoOAPositionStatus.V(3)
POSITION_STATUS_ERROR = ProtoOAPositionStatus.V(4)

global___ProtoOATradeSide = ProtoOATradeSide
class _ProtoOATradeSide(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOATradeSide.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    BUY = ProtoOATradeSide.V(1)
    SELL = ProtoOATradeSide.V(2)
class ProtoOATradeSide(metaclass=_ProtoOATradeSide):
    V = typing.NewType('V', builtins.int)
BUY = ProtoOATradeSide.V(1)
SELL = ProtoOATradeSide.V(2)

global___ProtoOAOrderType = ProtoOAOrderType
class _ProtoOAOrderType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAOrderType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    MARKET = ProtoOAOrderType.V(1)
    LIMIT = ProtoOAOrderType.V(2)
    STOP = ProtoOAOrderType.V(3)
    STOP_LOSS_TAKE_PROFIT = ProtoOAOrderType.V(4)
    MARKET_RANGE = ProtoOAOrderType.V(5)
    STOP_LIMIT = ProtoOAOrderType.V(6)
class ProtoOAOrderType(metaclass=_ProtoOAOrderType):
    V = typing.NewType('V', builtins.int)
MARKET = ProtoOAOrderType.V(1)
LIMIT = ProtoOAOrderType.V(2)
STOP = ProtoOAOrderType.V(3)
STOP_LOSS_TAKE_PROFIT = ProtoOAOrderType.V(4)
MARKET_RANGE = ProtoOAOrderType.V(5)
STOP_LIMIT = ProtoOAOrderType.V(6)

global___ProtoOATimeInForce = ProtoOATimeInForce
class _ProtoOATimeInForce(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOATimeInForce.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    GOOD_TILL_DATE = ProtoOATimeInForce.V(1)
    GOOD_TILL_CANCEL = ProtoOATimeInForce.V(2)
    IMMEDIATE_OR_CANCEL = ProtoOATimeInForce.V(3)
    FILL_OR_KILL = ProtoOATimeInForce.V(4)
    MARKET_ON_OPEN = ProtoOATimeInForce.V(5)
class ProtoOATimeInForce(metaclass=_ProtoOATimeInForce):
    V = typing.NewType('V', builtins.int)
GOOD_TILL_DATE = ProtoOATimeInForce.V(1)
GOOD_TILL_CANCEL = ProtoOATimeInForce.V(2)
IMMEDIATE_OR_CANCEL = ProtoOATimeInForce.V(3)
FILL_OR_KILL = ProtoOATimeInForce.V(4)
MARKET_ON_OPEN = ProtoOATimeInForce.V(5)

global___ProtoOAOrderStatus = ProtoOAOrderStatus
class _ProtoOAOrderStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAOrderStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ORDER_STATUS_ACCEPTED = ProtoOAOrderStatus.V(1)
    ORDER_STATUS_FILLED = ProtoOAOrderStatus.V(2)
    ORDER_STATUS_REJECTED = ProtoOAOrderStatus.V(3)
    ORDER_STATUS_EXPIRED = ProtoOAOrderStatus.V(4)
    ORDER_STATUS_CANCELLED = ProtoOAOrderStatus.V(5)
class ProtoOAOrderStatus(metaclass=_ProtoOAOrderStatus):
    V = typing.NewType('V', builtins.int)
ORDER_STATUS_ACCEPTED = ProtoOAOrderStatus.V(1)
ORDER_STATUS_FILLED = ProtoOAOrderStatus.V(2)
ORDER_STATUS_REJECTED = ProtoOAOrderStatus.V(3)
ORDER_STATUS_EXPIRED = ProtoOAOrderStatus.V(4)
ORDER_STATUS_CANCELLED = ProtoOAOrderStatus.V(5)

global___ProtoOAOrderTriggerMethod = ProtoOAOrderTriggerMethod
class _ProtoOAOrderTriggerMethod(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAOrderTriggerMethod.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    TRADE = ProtoOAOrderTriggerMethod.V(1)
    OPPOSITE = ProtoOAOrderTriggerMethod.V(2)
    DOUBLE_TRADE = ProtoOAOrderTriggerMethod.V(3)
    DOUBLE_OPPOSITE = ProtoOAOrderTriggerMethod.V(4)
class ProtoOAOrderTriggerMethod(metaclass=_ProtoOAOrderTriggerMethod):
    V = typing.NewType('V', builtins.int)
TRADE = ProtoOAOrderTriggerMethod.V(1)
OPPOSITE = ProtoOAOrderTriggerMethod.V(2)
DOUBLE_TRADE = ProtoOAOrderTriggerMethod.V(3)
DOUBLE_OPPOSITE = ProtoOAOrderTriggerMethod.V(4)

global___ProtoOAExecutionType = ProtoOAExecutionType
class _ProtoOAExecutionType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAExecutionType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ORDER_ACCEPTED = ProtoOAExecutionType.V(2)
    ORDER_FILLED = ProtoOAExecutionType.V(3)
    ORDER_REPLACED = ProtoOAExecutionType.V(4)
    ORDER_CANCELLED = ProtoOAExecutionType.V(5)
    ORDER_EXPIRED = ProtoOAExecutionType.V(6)
    ORDER_REJECTED = ProtoOAExecutionType.V(7)
    ORDER_CANCEL_REJECTED = ProtoOAExecutionType.V(8)
    SWAP = ProtoOAExecutionType.V(9)
    DEPOSIT_WITHDRAW = ProtoOAExecutionType.V(10)
    ORDER_PARTIAL_FILL = ProtoOAExecutionType.V(11)
    BONUS_DEPOSIT_WITHDRAW = ProtoOAExecutionType.V(12)
class ProtoOAExecutionType(metaclass=_ProtoOAExecutionType):
    V = typing.NewType('V', builtins.int)
ORDER_ACCEPTED = ProtoOAExecutionType.V(2)
ORDER_FILLED = ProtoOAExecutionType.V(3)
ORDER_REPLACED = ProtoOAExecutionType.V(4)
ORDER_CANCELLED = ProtoOAExecutionType.V(5)
ORDER_EXPIRED = ProtoOAExecutionType.V(6)
ORDER_REJECTED = ProtoOAExecutionType.V(7)
ORDER_CANCEL_REJECTED = ProtoOAExecutionType.V(8)
SWAP = ProtoOAExecutionType.V(9)
DEPOSIT_WITHDRAW = ProtoOAExecutionType.V(10)
ORDER_PARTIAL_FILL = ProtoOAExecutionType.V(11)
BONUS_DEPOSIT_WITHDRAW = ProtoOAExecutionType.V(12)

global___ProtoOAChangeBonusType = ProtoOAChangeBonusType
class _ProtoOAChangeBonusType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAChangeBonusType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    BONUS_DEPOSIT = ProtoOAChangeBonusType.V(0)
    BONUS_WITHDRAW = ProtoOAChangeBonusType.V(1)
class ProtoOAChangeBonusType(metaclass=_ProtoOAChangeBonusType):
    V = typing.NewType('V', builtins.int)
BONUS_DEPOSIT = ProtoOAChangeBonusType.V(0)
BONUS_WITHDRAW = ProtoOAChangeBonusType.V(1)

global___ProtoOAChangeBalanceType = ProtoOAChangeBalanceType
class _ProtoOAChangeBalanceType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAChangeBalanceType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    BALANCE_DEPOSIT = ProtoOAChangeBalanceType.V(0)
    BALANCE_WITHDRAW = ProtoOAChangeBalanceType.V(1)
    BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER = ProtoOAChangeBalanceType.V(3)
    BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER = ProtoOAChangeBalanceType.V(4)
    BALANCE_DEPOSIT_IB_COMMISSIONS = ProtoOAChangeBalanceType.V(5)
    BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE = ProtoOAChangeBalanceType.V(6)
    BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = ProtoOAChangeBalanceType.V(7)
    BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = ProtoOAChangeBalanceType.V(8)
    BALANCE_DEPOSIT_REBATE = ProtoOAChangeBalanceType.V(9)
    BALANCE_WITHDRAW_REBATE = ProtoOAChangeBalanceType.V(10)
    BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER = ProtoOAChangeBalanceType.V(11)
    BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER = ProtoOAChangeBalanceType.V(12)
    BALANCE_WITHDRAW_BONUS_COMPENSATION = ProtoOAChangeBalanceType.V(13)
    BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = ProtoOAChangeBalanceType.V(14)
    BALANCE_DEPOSIT_DIVIDENDS = ProtoOAChangeBalanceType.V(15)
    BALANCE_WITHDRAW_DIVIDENDS = ProtoOAChangeBalanceType.V(16)
    BALANCE_WITHDRAW_GSL_CHARGE = ProtoOAChangeBalanceType.V(17)
    BALANCE_WITHDRAW_ROLLOVER = ProtoOAChangeBalanceType.V(18)
    BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS = ProtoOAChangeBalanceType.V(19)
    BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS = ProtoOAChangeBalanceType.V(20)
    BALANCE_DEPOSIT_SWAP = ProtoOAChangeBalanceType.V(21)
    BALANCE_WITHDRAW_SWAP = ProtoOAChangeBalanceType.V(22)
    BALANCE_DEPOSIT_MANAGEMENT_FEE = ProtoOAChangeBalanceType.V(27)
    BALANCE_WITHDRAW_MANAGEMENT_FEE = ProtoOAChangeBalanceType.V(28)
    BALANCE_DEPOSIT_PERFORMANCE_FEE = ProtoOAChangeBalanceType.V(29)
    BALANCE_WITHDRAW_FOR_SUBACCOUNT = ProtoOAChangeBalanceType.V(30)
    BALANCE_DEPOSIT_TO_SUBACCOUNT = ProtoOAChangeBalanceType.V(31)
    BALANCE_WITHDRAW_FROM_SUBACCOUNT = ProtoOAChangeBalanceType.V(32)
    BALANCE_DEPOSIT_FROM_SUBACCOUNT = ProtoOAChangeBalanceType.V(33)
    BALANCE_WITHDRAW_COPY_FEE = ProtoOAChangeBalanceType.V(34)
    BALANCE_WITHDRAW_INACTIVITY_FEE = ProtoOAChangeBalanceType.V(35)
    BALANCE_DEPOSIT_TRANSFER = ProtoOAChangeBalanceType.V(36)
    BALANCE_WITHDRAW_TRANSFER = ProtoOAChangeBalanceType.V(37)
    BALANCE_DEPOSIT_CONVERTED_BONUS = ProtoOAChangeBalanceType.V(38)
class ProtoOAChangeBalanceType(metaclass=_ProtoOAChangeBalanceType):
    V = typing.NewType('V', builtins.int)
BALANCE_DEPOSIT = ProtoOAChangeBalanceType.V(0)
BALANCE_WITHDRAW = ProtoOAChangeBalanceType.V(1)
BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER = ProtoOAChangeBalanceType.V(3)
BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER = ProtoOAChangeBalanceType.V(4)
BALANCE_DEPOSIT_IB_COMMISSIONS = ProtoOAChangeBalanceType.V(5)
BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE = ProtoOAChangeBalanceType.V(6)
BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = ProtoOAChangeBalanceType.V(7)
BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = ProtoOAChangeBalanceType.V(8)
BALANCE_DEPOSIT_REBATE = ProtoOAChangeBalanceType.V(9)
BALANCE_WITHDRAW_REBATE = ProtoOAChangeBalanceType.V(10)
BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER = ProtoOAChangeBalanceType.V(11)
BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER = ProtoOAChangeBalanceType.V(12)
BALANCE_WITHDRAW_BONUS_COMPENSATION = ProtoOAChangeBalanceType.V(13)
BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = ProtoOAChangeBalanceType.V(14)
BALANCE_DEPOSIT_DIVIDENDS = ProtoOAChangeBalanceType.V(15)
BALANCE_WITHDRAW_DIVIDENDS = ProtoOAChangeBalanceType.V(16)
BALANCE_WITHDRAW_GSL_CHARGE = ProtoOAChangeBalanceType.V(17)
BALANCE_WITHDRAW_ROLLOVER = ProtoOAChangeBalanceType.V(18)
BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS = ProtoOAChangeBalanceType.V(19)
BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS = ProtoOAChangeBalanceType.V(20)
BALANCE_DEPOSIT_SWAP = ProtoOAChangeBalanceType.V(21)
BALANCE_WITHDRAW_SWAP = ProtoOAChangeBalanceType.V(22)
BALANCE_DEPOSIT_MANAGEMENT_FEE = ProtoOAChangeBalanceType.V(27)
BALANCE_WITHDRAW_MANAGEMENT_FEE = ProtoOAChangeBalanceType.V(28)
BALANCE_DEPOSIT_PERFORMANCE_FEE = ProtoOAChangeBalanceType.V(29)
BALANCE_WITHDRAW_FOR_SUBACCOUNT = ProtoOAChangeBalanceType.V(30)
BALANCE_DEPOSIT_TO_SUBACCOUNT = ProtoOAChangeBalanceType.V(31)
BALANCE_WITHDRAW_FROM_SUBACCOUNT = ProtoOAChangeBalanceType.V(32)
BALANCE_DEPOSIT_FROM_SUBACCOUNT = ProtoOAChangeBalanceType.V(33)
BALANCE_WITHDRAW_COPY_FEE = ProtoOAChangeBalanceType.V(34)
BALANCE_WITHDRAW_INACTIVITY_FEE = ProtoOAChangeBalanceType.V(35)
BALANCE_DEPOSIT_TRANSFER = ProtoOAChangeBalanceType.V(36)
BALANCE_WITHDRAW_TRANSFER = ProtoOAChangeBalanceType.V(37)
BALANCE_DEPOSIT_CONVERTED_BONUS = ProtoOAChangeBalanceType.V(38)

global___ProtoOADealStatus = ProtoOADealStatus
class _ProtoOADealStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOADealStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    FILLED = ProtoOADealStatus.V(2)
    PARTIALLY_FILLED = ProtoOADealStatus.V(3)
    REJECTED = ProtoOADealStatus.V(4)
    INTERNALLY_REJECTED = ProtoOADealStatus.V(5)
    ERROR = ProtoOADealStatus.V(6)
    MISSED = ProtoOADealStatus.V(7)
class ProtoOADealStatus(metaclass=_ProtoOADealStatus):
    V = typing.NewType('V', builtins.int)
FILLED = ProtoOADealStatus.V(2)
PARTIALLY_FILLED = ProtoOADealStatus.V(3)
REJECTED = ProtoOADealStatus.V(4)
INTERNALLY_REJECTED = ProtoOADealStatus.V(5)
ERROR = ProtoOADealStatus.V(6)
MISSED = ProtoOADealStatus.V(7)

global___ProtoOATrendbarPeriod = ProtoOATrendbarPeriod
class _ProtoOATrendbarPeriod(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOATrendbarPeriod.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    M1 = ProtoOATrendbarPeriod.V(1)
    M2 = ProtoOATrendbarPeriod.V(2)
    M3 = ProtoOATrendbarPeriod.V(3)
    M4 = ProtoOATrendbarPeriod.V(4)
    M5 = ProtoOATrendbarPeriod.V(5)
    M10 = ProtoOATrendbarPeriod.V(6)
    M15 = ProtoOATrendbarPeriod.V(7)
    M30 = ProtoOATrendbarPeriod.V(8)
    H1 = ProtoOATrendbarPeriod.V(9)
    H4 = ProtoOATrendbarPeriod.V(10)
    H12 = ProtoOATrendbarPeriod.V(11)
    D1 = ProtoOATrendbarPeriod.V(12)
    W1 = ProtoOATrendbarPeriod.V(13)
    MN1 = ProtoOATrendbarPeriod.V(14)
class ProtoOATrendbarPeriod(metaclass=_ProtoOATrendbarPeriod):
    V = typing.NewType('V', builtins.int)
M1 = ProtoOATrendbarPeriod.V(1)
M2 = ProtoOATrendbarPeriod.V(2)
M3 = ProtoOATrendbarPeriod.V(3)
M4 = ProtoOATrendbarPeriod.V(4)
M5 = ProtoOATrendbarPeriod.V(5)
M10 = ProtoOATrendbarPeriod.V(6)
M15 = ProtoOATrendbarPeriod.V(7)
M30 = ProtoOATrendbarPeriod.V(8)
H1 = ProtoOATrendbarPeriod.V(9)
H4 = ProtoOATrendbarPeriod.V(10)
H12 = ProtoOATrendbarPeriod.V(11)
D1 = ProtoOATrendbarPeriod.V(12)
W1 = ProtoOATrendbarPeriod.V(13)
MN1 = ProtoOATrendbarPeriod.V(14)

global___ProtoOAQuoteType = ProtoOAQuoteType
class _ProtoOAQuoteType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAQuoteType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    BID = ProtoOAQuoteType.V(1)
    ASK = ProtoOAQuoteType.V(2)
class ProtoOAQuoteType(metaclass=_ProtoOAQuoteType):
    V = typing.NewType('V', builtins.int)
BID = ProtoOAQuoteType.V(1)
ASK = ProtoOAQuoteType.V(2)

global___ProtoOAClientPermissionScope = ProtoOAClientPermissionScope
class _ProtoOAClientPermissionScope(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAClientPermissionScope.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    SCOPE_VIEW = ProtoOAClientPermissionScope.V(0)
    SCOPE_TRADE = ProtoOAClientPermissionScope.V(1)
class ProtoOAClientPermissionScope(metaclass=_ProtoOAClientPermissionScope):
    V = typing.NewType('V', builtins.int)
SCOPE_VIEW = ProtoOAClientPermissionScope.V(0)
SCOPE_TRADE = ProtoOAClientPermissionScope.V(1)

global___ProtoOANotificationType = ProtoOANotificationType
class _ProtoOANotificationType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOANotificationType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    MARGIN_LEVEL_THRESHOLD_1 = ProtoOANotificationType.V(61)
    MARGIN_LEVEL_THRESHOLD_2 = ProtoOANotificationType.V(62)
    MARGIN_LEVEL_THRESHOLD_3 = ProtoOANotificationType.V(63)
class ProtoOANotificationType(metaclass=_ProtoOANotificationType):
    V = typing.NewType('V', builtins.int)
MARGIN_LEVEL_THRESHOLD_1 = ProtoOANotificationType.V(61)
MARGIN_LEVEL_THRESHOLD_2 = ProtoOANotificationType.V(62)
MARGIN_LEVEL_THRESHOLD_3 = ProtoOANotificationType.V(63)

global___ProtoOAErrorCode = ProtoOAErrorCode
class _ProtoOAErrorCode(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOAErrorCode.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    OA_AUTH_TOKEN_EXPIRED = ProtoOAErrorCode.V(1)
    ACCOUNT_NOT_AUTHORIZED = ProtoOAErrorCode.V(2)
    ALREADY_LOGGED_IN = ProtoOAErrorCode.V(14)
    CH_CLIENT_AUTH_FAILURE = ProtoOAErrorCode.V(101)
    CH_CLIENT_NOT_AUTHENTICATED = ProtoOAErrorCode.V(102)
    CH_CLIENT_ALREADY_AUTHENTICATED = ProtoOAErrorCode.V(103)
    CH_ACCESS_TOKEN_INVALID = ProtoOAErrorCode.V(104)
    CH_SERVER_NOT_REACHABLE = ProtoOAErrorCode.V(105)
    CH_CTID_TRADER_ACCOUNT_NOT_FOUND = ProtoOAErrorCode.V(106)
    CH_OA_CLIENT_NOT_FOUND = ProtoOAErrorCode.V(107)
    REQUEST_FREQUENCY_EXCEEDED = ProtoOAErrorCode.V(108)
    SERVER_IS_UNDER_MAINTENANCE = ProtoOAErrorCode.V(109)
    CHANNEL_IS_BLOCKED = ProtoOAErrorCode.V(110)
    CONNECTIONS_LIMIT_EXCEEDED = ProtoOAErrorCode.V(67)
    WORSE_GSL_NOT_ALLOWED = ProtoOAErrorCode.V(68)
    SYMBOL_HAS_HOLIDAY = ProtoOAErrorCode.V(69)
    NOT_SUBSCRIBED_TO_SPOTS = ProtoOAErrorCode.V(112)
    ALREADY_SUBSCRIBED = ProtoOAErrorCode.V(113)
    SYMBOL_NOT_FOUND = ProtoOAErrorCode.V(114)
    UNKNOWN_SYMBOL = ProtoOAErrorCode.V(115)
    INCORRECT_BOUNDARIES = ProtoOAErrorCode.V(35)
    NO_QUOTES = ProtoOAErrorCode.V(117)
    NOT_ENOUGH_MONEY = ProtoOAErrorCode.V(118)
    MAX_EXPOSURE_REACHED = ProtoOAErrorCode.V(119)
    POSITION_NOT_FOUND = ProtoOAErrorCode.V(120)
    ORDER_NOT_FOUND = ProtoOAErrorCode.V(121)
    POSITION_NOT_OPEN = ProtoOAErrorCode.V(122)
    POSITION_LOCKED = ProtoOAErrorCode.V(123)
    TOO_MANY_POSITIONS = ProtoOAErrorCode.V(124)
    TRADING_BAD_VOLUME = ProtoOAErrorCode.V(125)
    TRADING_BAD_STOPS = ProtoOAErrorCode.V(126)
    TRADING_BAD_PRICES = ProtoOAErrorCode.V(127)
    TRADING_BAD_STAKE = ProtoOAErrorCode.V(128)
    PROTECTION_IS_TOO_CLOSE_TO_MARKET = ProtoOAErrorCode.V(129)
    TRADING_BAD_EXPIRATION_DATE = ProtoOAErrorCode.V(130)
    PENDING_EXECUTION = ProtoOAErrorCode.V(131)
    TRADING_DISABLED = ProtoOAErrorCode.V(132)
    TRADING_NOT_ALLOWED = ProtoOAErrorCode.V(133)
    UNABLE_TO_CANCEL_ORDER = ProtoOAErrorCode.V(134)
    UNABLE_TO_AMEND_ORDER = ProtoOAErrorCode.V(135)
    SHORT_SELLING_NOT_ALLOWED = ProtoOAErrorCode.V(136)
class ProtoOAErrorCode(metaclass=_ProtoOAErrorCode):
    V = typing.NewType('V', builtins.int)
OA_AUTH_TOKEN_EXPIRED = ProtoOAErrorCode.V(1)
ACCOUNT_NOT_AUTHORIZED = ProtoOAErrorCode.V(2)
ALREADY_LOGGED_IN = ProtoOAErrorCode.V(14)
CH_CLIENT_AUTH_FAILURE = ProtoOAErrorCode.V(101)
CH_CLIENT_NOT_AUTHENTICATED = ProtoOAErrorCode.V(102)
CH_CLIENT_ALREADY_AUTHENTICATED = ProtoOAErrorCode.V(103)
CH_ACCESS_TOKEN_INVALID = ProtoOAErrorCode.V(104)
CH_SERVER_NOT_REACHABLE = ProtoOAErrorCode.V(105)
CH_CTID_TRADER_ACCOUNT_NOT_FOUND = ProtoOAErrorCode.V(106)
CH_OA_CLIENT_NOT_FOUND = ProtoOAErrorCode.V(107)
REQUEST_FREQUENCY_EXCEEDED = ProtoOAErrorCode.V(108)
SERVER_IS_UNDER_MAINTENANCE = ProtoOAErrorCode.V(109)
CHANNEL_IS_BLOCKED = ProtoOAErrorCode.V(110)
CONNECTIONS_LIMIT_EXCEEDED = ProtoOAErrorCode.V(67)
WORSE_GSL_NOT_ALLOWED = ProtoOAErrorCode.V(68)
SYMBOL_HAS_HOLIDAY = ProtoOAErrorCode.V(69)
NOT_SUBSCRIBED_TO_SPOTS = ProtoOAErrorCode.V(112)
ALREADY_SUBSCRIBED = ProtoOAErrorCode.V(113)
SYMBOL_NOT_FOUND = ProtoOAErrorCode.V(114)
UNKNOWN_SYMBOL = ProtoOAErrorCode.V(115)
INCORRECT_BOUNDARIES = ProtoOAErrorCode.V(35)
NO_QUOTES = ProtoOAErrorCode.V(117)
NOT_ENOUGH_MONEY = ProtoOAErrorCode.V(118)
MAX_EXPOSURE_REACHED = ProtoOAErrorCode.V(119)
POSITION_NOT_FOUND = ProtoOAErrorCode.V(120)
ORDER_NOT_FOUND = ProtoOAErrorCode.V(121)
POSITION_NOT_OPEN = ProtoOAErrorCode.V(122)
POSITION_LOCKED = ProtoOAErrorCode.V(123)
TOO_MANY_POSITIONS = ProtoOAErrorCode.V(124)
TRADING_BAD_VOLUME = ProtoOAErrorCode.V(125)
TRADING_BAD_STOPS = ProtoOAErrorCode.V(126)
TRADING_BAD_PRICES = ProtoOAErrorCode.V(127)
TRADING_BAD_STAKE = ProtoOAErrorCode.V(128)
PROTECTION_IS_TOO_CLOSE_TO_MARKET = ProtoOAErrorCode.V(129)
TRADING_BAD_EXPIRATION_DATE = ProtoOAErrorCode.V(130)
PENDING_EXECUTION = ProtoOAErrorCode.V(131)
TRADING_DISABLED = ProtoOAErrorCode.V(132)
TRADING_NOT_ALLOWED = ProtoOAErrorCode.V(133)
UNABLE_TO_CANCEL_ORDER = ProtoOAErrorCode.V(134)
UNABLE_TO_AMEND_ORDER = ProtoOAErrorCode.V(135)
SHORT_SELLING_NOT_ALLOWED = ProtoOAErrorCode.V(136)

global___ProtoOALimitedRiskMarginCalculationStrategy = ProtoOALimitedRiskMarginCalculationStrategy
class _ProtoOALimitedRiskMarginCalculationStrategy(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtoOALimitedRiskMarginCalculationStrategy.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ACCORDING_TO_LEVERAGE = ProtoOALimitedRiskMarginCalculationStrategy.V(0)
    ACCORDING_TO_GSL = ProtoOALimitedRiskMarginCalculationStrategy.V(1)
    ACCORDING_TO_GSL_AND_LEVERAGE = ProtoOALimitedRiskMarginCalculationStrategy.V(2)
class ProtoOALimitedRiskMarginCalculationStrategy(metaclass=_ProtoOALimitedRiskMarginCalculationStrategy):
    V = typing.NewType('V', builtins.int)
ACCORDING_TO_LEVERAGE = ProtoOALimitedRiskMarginCalculationStrategy.V(0)
ACCORDING_TO_GSL = ProtoOALimitedRiskMarginCalculationStrategy.V(1)
ACCORDING_TO_GSL_AND_LEVERAGE = ProtoOALimitedRiskMarginCalculationStrategy.V(2)

class ProtoOAAsset(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ASSETID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DISPLAYNAME_FIELD_NUMBER: builtins.int
    DIGITS_FIELD_NUMBER: builtins.int
    assetId: builtins.int = ...
    name: typing.Text = ...
    displayName: typing.Text = ...
    digits: builtins.int = ...

    def __init__(self,
        *,
        assetId : typing.Optional[builtins.int] = ...,
        name : typing.Optional[typing.Text] = ...,
        displayName : typing.Optional[typing.Text] = ...,
        digits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"assetId",b"assetId",u"digits",b"digits",u"displayName",b"displayName",u"name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"assetId",b"assetId",u"digits",b"digits",u"displayName",b"displayName",u"name",b"name"]) -> None: ...
global___ProtoOAAsset = ProtoOAAsset

class ProtoOASymbol(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SYMBOLID_FIELD_NUMBER: builtins.int
    DIGITS_FIELD_NUMBER: builtins.int
    PIPPOSITION_FIELD_NUMBER: builtins.int
    ENABLESHORTSELLING_FIELD_NUMBER: builtins.int
    GUARANTEEDSTOPLOSS_FIELD_NUMBER: builtins.int
    SWAPROLLOVER3DAYS_FIELD_NUMBER: builtins.int
    SWAPLONG_FIELD_NUMBER: builtins.int
    SWAPSHORT_FIELD_NUMBER: builtins.int
    MAXVOLUME_FIELD_NUMBER: builtins.int
    MINVOLUME_FIELD_NUMBER: builtins.int
    STEPVOLUME_FIELD_NUMBER: builtins.int
    MAXEXPOSURE_FIELD_NUMBER: builtins.int
    SCHEDULE_FIELD_NUMBER: builtins.int
    COMMISSION_FIELD_NUMBER: builtins.int
    COMMISSIONTYPE_FIELD_NUMBER: builtins.int
    SLDISTANCE_FIELD_NUMBER: builtins.int
    TPDISTANCE_FIELD_NUMBER: builtins.int
    GSLDISTANCE_FIELD_NUMBER: builtins.int
    GSLCHARGE_FIELD_NUMBER: builtins.int
    DISTANCESETIN_FIELD_NUMBER: builtins.int
    MINCOMMISSION_FIELD_NUMBER: builtins.int
    MINCOMMISSIONTYPE_FIELD_NUMBER: builtins.int
    MINCOMMISSIONASSET_FIELD_NUMBER: builtins.int
    ROLLOVERCOMMISSION_FIELD_NUMBER: builtins.int
    SKIPROLLOVERDAYS_FIELD_NUMBER: builtins.int
    SCHEDULETIMEZONE_FIELD_NUMBER: builtins.int
    TRADINGMODE_FIELD_NUMBER: builtins.int
    ROLLOVERCOMMISSION3DAYS_FIELD_NUMBER: builtins.int
    SWAPCALCULATIONTYPE_FIELD_NUMBER: builtins.int
    LOTSIZE_FIELD_NUMBER: builtins.int
    PRECISETRADINGCOMMISSIONRATE_FIELD_NUMBER: builtins.int
    PRECISEMINCOMMISSION_FIELD_NUMBER: builtins.int
    HOLIDAY_FIELD_NUMBER: builtins.int
    symbolId: builtins.int = ...
    digits: builtins.int = ...
    pipPosition: builtins.int = ...
    enableShortSelling: builtins.bool = ...
    guaranteedStopLoss: builtins.bool = ...
    swapRollover3Days: global___ProtoOADayOfWeek.V = ...
    swapLong: builtins.float = ...
    swapShort: builtins.float = ...
    maxVolume: builtins.int = ...
    minVolume: builtins.int = ...
    stepVolume: builtins.int = ...
    maxExposure: builtins.int = ...
    commission: builtins.int = ...
    commissionType: global___ProtoOACommissionType.V = ...
    slDistance: builtins.int = ...
    tpDistance: builtins.int = ...
    gslDistance: builtins.int = ...
    gslCharge: builtins.int = ...
    distanceSetIn: global___ProtoOASymbolDistanceType.V = ...
    minCommission: builtins.int = ...
    minCommissionType: global___ProtoOAMinCommissionType.V = ...
    minCommissionAsset: typing.Text = ...
    rolloverCommission: builtins.int = ...
    skipRolloverDays: builtins.int = ...
    scheduleTimeZone: typing.Text = ...
    tradingMode: global___ProtoOATradingMode.V = ...
    rolloverCommission3Days: global___ProtoOADayOfWeek.V = ...
    swapCalculationType: global___ProtoOASwapCalculationType.V = ...
    lotSize: builtins.int = ...
    preciseTradingCommissionRate: builtins.int = ...
    preciseMinCommission: builtins.int = ...

    @property
    def schedule(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtoOAInterval]: ...

    @property
    def holiday(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtoOAHoliday]: ...

    def __init__(self,
        *,
        symbolId : typing.Optional[builtins.int] = ...,
        digits : typing.Optional[builtins.int] = ...,
        pipPosition : typing.Optional[builtins.int] = ...,
        enableShortSelling : typing.Optional[builtins.bool] = ...,
        guaranteedStopLoss : typing.Optional[builtins.bool] = ...,
        swapRollover3Days : typing.Optional[global___ProtoOADayOfWeek.V] = ...,
        swapLong : typing.Optional[builtins.float] = ...,
        swapShort : typing.Optional[builtins.float] = ...,
        maxVolume : typing.Optional[builtins.int] = ...,
        minVolume : typing.Optional[builtins.int] = ...,
        stepVolume : typing.Optional[builtins.int] = ...,
        maxExposure : typing.Optional[builtins.int] = ...,
        schedule : typing.Optional[typing.Iterable[global___ProtoOAInterval]] = ...,
        commission : typing.Optional[builtins.int] = ...,
        commissionType : typing.Optional[global___ProtoOACommissionType.V] = ...,
        slDistance : typing.Optional[builtins.int] = ...,
        tpDistance : typing.Optional[builtins.int] = ...,
        gslDistance : typing.Optional[builtins.int] = ...,
        gslCharge : typing.Optional[builtins.int] = ...,
        distanceSetIn : typing.Optional[global___ProtoOASymbolDistanceType.V] = ...,
        minCommission : typing.Optional[builtins.int] = ...,
        minCommissionType : typing.Optional[global___ProtoOAMinCommissionType.V] = ...,
        minCommissionAsset : typing.Optional[typing.Text] = ...,
        rolloverCommission : typing.Optional[builtins.int] = ...,
        skipRolloverDays : typing.Optional[builtins.int] = ...,
        scheduleTimeZone : typing.Optional[typing.Text] = ...,
        tradingMode : typing.Optional[global___ProtoOATradingMode.V] = ...,
        rolloverCommission3Days : typing.Optional[global___ProtoOADayOfWeek.V] = ...,
        swapCalculationType : typing.Optional[global___ProtoOASwapCalculationType.V] = ...,
        lotSize : typing.Optional[builtins.int] = ...,
        preciseTradingCommissionRate : typing.Optional[builtins.int] = ...,
        preciseMinCommission : typing.Optional[builtins.int] = ...,
        holiday : typing.Optional[typing.Iterable[global___ProtoOAHoliday]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"commission",b"commission",u"commissionType",b"commissionType",u"digits",b"digits",u"distanceSetIn",b"distanceSetIn",u"enableShortSelling",b"enableShortSelling",u"gslCharge",b"gslCharge",u"gslDistance",b"gslDistance",u"guaranteedStopLoss",b"guaranteedStopLoss",u"lotSize",b"lotSize",u"maxExposure",b"maxExposure",u"maxVolume",b"maxVolume",u"minCommission",b"minCommission",u"minCommissionAsset",b"minCommissionAsset",u"minCommissionType",b"minCommissionType",u"minVolume",b"minVolume",u"pipPosition",b"pipPosition",u"preciseMinCommission",b"preciseMinCommission",u"preciseTradingCommissionRate",b"preciseTradingCommissionRate",u"rolloverCommission",b"rolloverCommission",u"rolloverCommission3Days",b"rolloverCommission3Days",u"scheduleTimeZone",b"scheduleTimeZone",u"skipRolloverDays",b"skipRolloverDays",u"slDistance",b"slDistance",u"stepVolume",b"stepVolume",u"swapCalculationType",b"swapCalculationType",u"swapLong",b"swapLong",u"swapRollover3Days",b"swapRollover3Days",u"swapShort",b"swapShort",u"symbolId",b"symbolId",u"tpDistance",b"tpDistance",u"tradingMode",b"tradingMode"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"commission",b"commission",u"commissionType",b"commissionType",u"digits",b"digits",u"distanceSetIn",b"distanceSetIn",u"enableShortSelling",b"enableShortSelling",u"gslCharge",b"gslCharge",u"gslDistance",b"gslDistance",u"guaranteedStopLoss",b"guaranteedStopLoss",u"holiday",b"holiday",u"lotSize",b"lotSize",u"maxExposure",b"maxExposure",u"maxVolume",b"maxVolume",u"minCommission",b"minCommission",u"minCommissionAsset",b"minCommissionAsset",u"minCommissionType",b"minCommissionType",u"minVolume",b"minVolume",u"pipPosition",b"pipPosition",u"preciseMinCommission",b"preciseMinCommission",u"preciseTradingCommissionRate",b"preciseTradingCommissionRate",u"rolloverCommission",b"rolloverCommission",u"rolloverCommission3Days",b"rolloverCommission3Days",u"schedule",b"schedule",u"scheduleTimeZone",b"scheduleTimeZone",u"skipRolloverDays",b"skipRolloverDays",u"slDistance",b"slDistance",u"stepVolume",b"stepVolume",u"swapCalculationType",b"swapCalculationType",u"swapLong",b"swapLong",u"swapRollover3Days",b"swapRollover3Days",u"swapShort",b"swapShort",u"symbolId",b"symbolId",u"tpDistance",b"tpDistance",u"tradingMode",b"tradingMode"]) -> None: ...
global___ProtoOASymbol = ProtoOASymbol

class ProtoOALightSymbol(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SYMBOLID_FIELD_NUMBER: builtins.int
    SYMBOLNAME_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    BASEASSETID_FIELD_NUMBER: builtins.int
    QUOTEASSETID_FIELD_NUMBER: builtins.int
    SYMBOLCATEGORYID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    symbolId: builtins.int = ...
    symbolName: typing.Text = ...
    enabled: builtins.bool = ...
    baseAssetId: builtins.int = ...
    quoteAssetId: builtins.int = ...
    symbolCategoryId: builtins.int = ...
    description: typing.Text = ...

    def __init__(self,
        *,
        symbolId : typing.Optional[builtins.int] = ...,
        symbolName : typing.Optional[typing.Text] = ...,
        enabled : typing.Optional[builtins.bool] = ...,
        baseAssetId : typing.Optional[builtins.int] = ...,
        quoteAssetId : typing.Optional[builtins.int] = ...,
        symbolCategoryId : typing.Optional[builtins.int] = ...,
        description : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"baseAssetId",b"baseAssetId",u"description",b"description",u"enabled",b"enabled",u"quoteAssetId",b"quoteAssetId",u"symbolCategoryId",b"symbolCategoryId",u"symbolId",b"symbolId",u"symbolName",b"symbolName"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"baseAssetId",b"baseAssetId",u"description",b"description",u"enabled",b"enabled",u"quoteAssetId",b"quoteAssetId",u"symbolCategoryId",b"symbolCategoryId",u"symbolId",b"symbolId",u"symbolName",b"symbolName"]) -> None: ...
global___ProtoOALightSymbol = ProtoOALightSymbol

class ProtoOAArchivedSymbol(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SYMBOLID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    UTCLASTUPDATETIMESTAMP_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    symbolId: builtins.int = ...
    name: typing.Text = ...
    utcLastUpdateTimestamp: builtins.int = ...
    description: typing.Text = ...

    def __init__(self,
        *,
        symbolId : typing.Optional[builtins.int] = ...,
        name : typing.Optional[typing.Text] = ...,
        utcLastUpdateTimestamp : typing.Optional[builtins.int] = ...,
        description : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"description",b"description",u"name",b"name",u"symbolId",b"symbolId",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"description",b"description",u"name",b"name",u"symbolId",b"symbolId",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> None: ...
global___ProtoOAArchivedSymbol = ProtoOAArchivedSymbol

class ProtoOASymbolCategory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    ASSETCLASSID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.int = ...
    assetClassId: builtins.int = ...
    name: typing.Text = ...

    def __init__(self,
        *,
        id : typing.Optional[builtins.int] = ...,
        assetClassId : typing.Optional[builtins.int] = ...,
        name : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"assetClassId",b"assetClassId",u"id",b"id",u"name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"assetClassId",b"assetClassId",u"id",b"id",u"name",b"name"]) -> None: ...
global___ProtoOASymbolCategory = ProtoOASymbolCategory

class ProtoOAInterval(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STARTSECOND_FIELD_NUMBER: builtins.int
    ENDSECOND_FIELD_NUMBER: builtins.int
    startSecond: builtins.int = ...
    endSecond: builtins.int = ...

    def __init__(self,
        *,
        startSecond : typing.Optional[builtins.int] = ...,
        endSecond : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"endSecond",b"endSecond",u"startSecond",b"startSecond"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"endSecond",b"endSecond",u"startSecond",b"startSecond"]) -> None: ...
global___ProtoOAInterval = ProtoOAInterval

class ProtoOATrader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CTIDTRADERACCOUNTID_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    BALANCEVERSION_FIELD_NUMBER: builtins.int
    MANAGERBONUS_FIELD_NUMBER: builtins.int
    IBBONUS_FIELD_NUMBER: builtins.int
    NONWITHDRAWABLEBONUS_FIELD_NUMBER: builtins.int
    ACCESSRIGHTS_FIELD_NUMBER: builtins.int
    DEPOSITASSETID_FIELD_NUMBER: builtins.int
    SWAPFREE_FIELD_NUMBER: builtins.int
    LEVERAGEINCENTS_FIELD_NUMBER: builtins.int
    TOTALMARGINCALCULATIONTYPE_FIELD_NUMBER: builtins.int
    MAXLEVERAGE_FIELD_NUMBER: builtins.int
    FRENCHRISK_FIELD_NUMBER: builtins.int
    TRADERLOGIN_FIELD_NUMBER: builtins.int
    ACCOUNTTYPE_FIELD_NUMBER: builtins.int
    BROKERNAME_FIELD_NUMBER: builtins.int
    REGISTRATIONTIMESTAMP_FIELD_NUMBER: builtins.int
    ISLIMITEDRISK_FIELD_NUMBER: builtins.int
    LIMITEDRISKMARGINCALCULATIONSTRATEGY_FIELD_NUMBER: builtins.int
    MONEYDIGITS_FIELD_NUMBER: builtins.int
    ctidTraderAccountId: builtins.int = ...
    balance: builtins.int = ...
    balanceVersion: builtins.int = ...
    managerBonus: builtins.int = ...
    ibBonus: builtins.int = ...
    nonWithdrawableBonus: builtins.int = ...
    accessRights: global___ProtoOAAccessRights.V = ...
    depositAssetId: builtins.int = ...
    swapFree: builtins.bool = ...
    leverageInCents: builtins.int = ...
    totalMarginCalculationType: global___ProtoOATotalMarginCalculationType.V = ...
    maxLeverage: builtins.int = ...
    frenchRisk: builtins.bool = ...
    traderLogin: builtins.int = ...
    accountType: global___ProtoOAAccountType.V = ...
    brokerName: typing.Text = ...
    registrationTimestamp: builtins.int = ...
    isLimitedRisk: builtins.bool = ...
    limitedRiskMarginCalculationStrategy: global___ProtoOALimitedRiskMarginCalculationStrategy.V = ...
    moneyDigits: builtins.int = ...

    def __init__(self,
        *,
        ctidTraderAccountId : typing.Optional[builtins.int] = ...,
        balance : typing.Optional[builtins.int] = ...,
        balanceVersion : typing.Optional[builtins.int] = ...,
        managerBonus : typing.Optional[builtins.int] = ...,
        ibBonus : typing.Optional[builtins.int] = ...,
        nonWithdrawableBonus : typing.Optional[builtins.int] = ...,
        accessRights : typing.Optional[global___ProtoOAAccessRights.V] = ...,
        depositAssetId : typing.Optional[builtins.int] = ...,
        swapFree : typing.Optional[builtins.bool] = ...,
        leverageInCents : typing.Optional[builtins.int] = ...,
        totalMarginCalculationType : typing.Optional[global___ProtoOATotalMarginCalculationType.V] = ...,
        maxLeverage : typing.Optional[builtins.int] = ...,
        frenchRisk : typing.Optional[builtins.bool] = ...,
        traderLogin : typing.Optional[builtins.int] = ...,
        accountType : typing.Optional[global___ProtoOAAccountType.V] = ...,
        brokerName : typing.Optional[typing.Text] = ...,
        registrationTimestamp : typing.Optional[builtins.int] = ...,
        isLimitedRisk : typing.Optional[builtins.bool] = ...,
        limitedRiskMarginCalculationStrategy : typing.Optional[global___ProtoOALimitedRiskMarginCalculationStrategy.V] = ...,
        moneyDigits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"accessRights",b"accessRights",u"accountType",b"accountType",u"balance",b"balance",u"balanceVersion",b"balanceVersion",u"brokerName",b"brokerName",u"ctidTraderAccountId",b"ctidTraderAccountId",u"depositAssetId",b"depositAssetId",u"frenchRisk",b"frenchRisk",u"ibBonus",b"ibBonus",u"isLimitedRisk",b"isLimitedRisk",u"leverageInCents",b"leverageInCents",u"limitedRiskMarginCalculationStrategy",b"limitedRiskMarginCalculationStrategy",u"managerBonus",b"managerBonus",u"maxLeverage",b"maxLeverage",u"moneyDigits",b"moneyDigits",u"nonWithdrawableBonus",b"nonWithdrawableBonus",u"registrationTimestamp",b"registrationTimestamp",u"swapFree",b"swapFree",u"totalMarginCalculationType",b"totalMarginCalculationType",u"traderLogin",b"traderLogin"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"accessRights",b"accessRights",u"accountType",b"accountType",u"balance",b"balance",u"balanceVersion",b"balanceVersion",u"brokerName",b"brokerName",u"ctidTraderAccountId",b"ctidTraderAccountId",u"depositAssetId",b"depositAssetId",u"frenchRisk",b"frenchRisk",u"ibBonus",b"ibBonus",u"isLimitedRisk",b"isLimitedRisk",u"leverageInCents",b"leverageInCents",u"limitedRiskMarginCalculationStrategy",b"limitedRiskMarginCalculationStrategy",u"managerBonus",b"managerBonus",u"maxLeverage",b"maxLeverage",u"moneyDigits",b"moneyDigits",u"nonWithdrawableBonus",b"nonWithdrawableBonus",u"registrationTimestamp",b"registrationTimestamp",u"swapFree",b"swapFree",u"totalMarginCalculationType",b"totalMarginCalculationType",u"traderLogin",b"traderLogin"]) -> None: ...
global___ProtoOATrader = ProtoOATrader

class ProtoOAPosition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POSITIONID_FIELD_NUMBER: builtins.int
    TRADEDATA_FIELD_NUMBER: builtins.int
    POSITIONSTATUS_FIELD_NUMBER: builtins.int
    SWAP_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    STOPLOSS_FIELD_NUMBER: builtins.int
    TAKEPROFIT_FIELD_NUMBER: builtins.int
    UTCLASTUPDATETIMESTAMP_FIELD_NUMBER: builtins.int
    COMMISSION_FIELD_NUMBER: builtins.int
    MARGINRATE_FIELD_NUMBER: builtins.int
    MIRRORINGCOMMISSION_FIELD_NUMBER: builtins.int
    GUARANTEEDSTOPLOSS_FIELD_NUMBER: builtins.int
    USEDMARGIN_FIELD_NUMBER: builtins.int
    STOPLOSSTRIGGERMETHOD_FIELD_NUMBER: builtins.int
    MONEYDIGITS_FIELD_NUMBER: builtins.int
    positionId: builtins.int = ...
    positionStatus: global___ProtoOAPositionStatus.V = ...
    swap: builtins.int = ...
    price: builtins.float = ...
    stopLoss: builtins.float = ...
    takeProfit: builtins.float = ...
    utcLastUpdateTimestamp: builtins.int = ...
    commission: builtins.int = ...
    marginRate: builtins.float = ...
    mirroringCommission: builtins.int = ...
    guaranteedStopLoss: builtins.bool = ...
    usedMargin: builtins.int = ...
    stopLossTriggerMethod: global___ProtoOAOrderTriggerMethod.V = ...
    moneyDigits: builtins.int = ...

    @property
    def tradeData(self) -> global___ProtoOATradeData: ...

    def __init__(self,
        *,
        positionId : typing.Optional[builtins.int] = ...,
        tradeData : typing.Optional[global___ProtoOATradeData] = ...,
        positionStatus : typing.Optional[global___ProtoOAPositionStatus.V] = ...,
        swap : typing.Optional[builtins.int] = ...,
        price : typing.Optional[builtins.float] = ...,
        stopLoss : typing.Optional[builtins.float] = ...,
        takeProfit : typing.Optional[builtins.float] = ...,
        utcLastUpdateTimestamp : typing.Optional[builtins.int] = ...,
        commission : typing.Optional[builtins.int] = ...,
        marginRate : typing.Optional[builtins.float] = ...,
        mirroringCommission : typing.Optional[builtins.int] = ...,
        guaranteedStopLoss : typing.Optional[builtins.bool] = ...,
        usedMargin : typing.Optional[builtins.int] = ...,
        stopLossTriggerMethod : typing.Optional[global___ProtoOAOrderTriggerMethod.V] = ...,
        moneyDigits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"commission",b"commission",u"guaranteedStopLoss",b"guaranteedStopLoss",u"marginRate",b"marginRate",u"mirroringCommission",b"mirroringCommission",u"moneyDigits",b"moneyDigits",u"positionId",b"positionId",u"positionStatus",b"positionStatus",u"price",b"price",u"stopLoss",b"stopLoss",u"stopLossTriggerMethod",b"stopLossTriggerMethod",u"swap",b"swap",u"takeProfit",b"takeProfit",u"tradeData",b"tradeData",u"usedMargin",b"usedMargin",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"commission",b"commission",u"guaranteedStopLoss",b"guaranteedStopLoss",u"marginRate",b"marginRate",u"mirroringCommission",b"mirroringCommission",u"moneyDigits",b"moneyDigits",u"positionId",b"positionId",u"positionStatus",b"positionStatus",u"price",b"price",u"stopLoss",b"stopLoss",u"stopLossTriggerMethod",b"stopLossTriggerMethod",u"swap",b"swap",u"takeProfit",b"takeProfit",u"tradeData",b"tradeData",u"usedMargin",b"usedMargin",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> None: ...
global___ProtoOAPosition = ProtoOAPosition

class ProtoOATradeData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SYMBOLID_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    TRADESIDE_FIELD_NUMBER: builtins.int
    OPENTIMESTAMP_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    GUARANTEEDSTOPLOSS_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    symbolId: builtins.int = ...
    volume: builtins.int = ...
    tradeSide: global___ProtoOATradeSide.V = ...
    openTimestamp: builtins.int = ...
    label: typing.Text = ...
    guaranteedStopLoss: builtins.bool = ...
    comment: typing.Text = ...

    def __init__(self,
        *,
        symbolId : typing.Optional[builtins.int] = ...,
        volume : typing.Optional[builtins.int] = ...,
        tradeSide : typing.Optional[global___ProtoOATradeSide.V] = ...,
        openTimestamp : typing.Optional[builtins.int] = ...,
        label : typing.Optional[typing.Text] = ...,
        guaranteedStopLoss : typing.Optional[builtins.bool] = ...,
        comment : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"comment",b"comment",u"guaranteedStopLoss",b"guaranteedStopLoss",u"label",b"label",u"openTimestamp",b"openTimestamp",u"symbolId",b"symbolId",u"tradeSide",b"tradeSide",u"volume",b"volume"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"comment",b"comment",u"guaranteedStopLoss",b"guaranteedStopLoss",u"label",b"label",u"openTimestamp",b"openTimestamp",u"symbolId",b"symbolId",u"tradeSide",b"tradeSide",u"volume",b"volume"]) -> None: ...
global___ProtoOATradeData = ProtoOATradeData

class ProtoOAOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ORDERID_FIELD_NUMBER: builtins.int
    TRADEDATA_FIELD_NUMBER: builtins.int
    ORDERTYPE_FIELD_NUMBER: builtins.int
    ORDERSTATUS_FIELD_NUMBER: builtins.int
    EXPIRATIONTIMESTAMP_FIELD_NUMBER: builtins.int
    EXECUTIONPRICE_FIELD_NUMBER: builtins.int
    EXECUTEDVOLUME_FIELD_NUMBER: builtins.int
    UTCLASTUPDATETIMESTAMP_FIELD_NUMBER: builtins.int
    BASESLIPPAGEPRICE_FIELD_NUMBER: builtins.int
    SLIPPAGEINPOINTS_FIELD_NUMBER: builtins.int
    CLOSINGORDER_FIELD_NUMBER: builtins.int
    LIMITPRICE_FIELD_NUMBER: builtins.int
    STOPPRICE_FIELD_NUMBER: builtins.int
    STOPLOSS_FIELD_NUMBER: builtins.int
    TAKEPROFIT_FIELD_NUMBER: builtins.int
    CLIENTORDERID_FIELD_NUMBER: builtins.int
    TIMEINFORCE_FIELD_NUMBER: builtins.int
    POSITIONID_FIELD_NUMBER: builtins.int
    RELATIVESTOPLOSS_FIELD_NUMBER: builtins.int
    RELATIVETAKEPROFIT_FIELD_NUMBER: builtins.int
    ISSTOPOUT_FIELD_NUMBER: builtins.int
    TRAILINGSTOPLOSS_FIELD_NUMBER: builtins.int
    STOPTRIGGERMETHOD_FIELD_NUMBER: builtins.int
    orderId: builtins.int = ...
    orderType: global___ProtoOAOrderType.V = ...
    orderStatus: global___ProtoOAOrderStatus.V = ...
    expirationTimestamp: builtins.int = ...
    executionPrice: builtins.float = ...
    executedVolume: builtins.int = ...
    utcLastUpdateTimestamp: builtins.int = ...
    baseSlippagePrice: builtins.float = ...
    slippageInPoints: builtins.int = ...
    closingOrder: builtins.bool = ...
    limitPrice: builtins.float = ...
    stopPrice: builtins.float = ...
    stopLoss: builtins.float = ...
    takeProfit: builtins.float = ...
    clientOrderId: typing.Text = ...
    timeInForce: global___ProtoOATimeInForce.V = ...
    positionId: builtins.int = ...
    relativeStopLoss: builtins.int = ...
    relativeTakeProfit: builtins.int = ...
    isStopOut: builtins.bool = ...
    trailingStopLoss: builtins.bool = ...
    stopTriggerMethod: global___ProtoOAOrderTriggerMethod.V = ...

    @property
    def tradeData(self) -> global___ProtoOATradeData: ...

    def __init__(self,
        *,
        orderId : typing.Optional[builtins.int] = ...,
        tradeData : typing.Optional[global___ProtoOATradeData] = ...,
        orderType : typing.Optional[global___ProtoOAOrderType.V] = ...,
        orderStatus : typing.Optional[global___ProtoOAOrderStatus.V] = ...,
        expirationTimestamp : typing.Optional[builtins.int] = ...,
        executionPrice : typing.Optional[builtins.float] = ...,
        executedVolume : typing.Optional[builtins.int] = ...,
        utcLastUpdateTimestamp : typing.Optional[builtins.int] = ...,
        baseSlippagePrice : typing.Optional[builtins.float] = ...,
        slippageInPoints : typing.Optional[builtins.int] = ...,
        closingOrder : typing.Optional[builtins.bool] = ...,
        limitPrice : typing.Optional[builtins.float] = ...,
        stopPrice : typing.Optional[builtins.float] = ...,
        stopLoss : typing.Optional[builtins.float] = ...,
        takeProfit : typing.Optional[builtins.float] = ...,
        clientOrderId : typing.Optional[typing.Text] = ...,
        timeInForce : typing.Optional[global___ProtoOATimeInForce.V] = ...,
        positionId : typing.Optional[builtins.int] = ...,
        relativeStopLoss : typing.Optional[builtins.int] = ...,
        relativeTakeProfit : typing.Optional[builtins.int] = ...,
        isStopOut : typing.Optional[builtins.bool] = ...,
        trailingStopLoss : typing.Optional[builtins.bool] = ...,
        stopTriggerMethod : typing.Optional[global___ProtoOAOrderTriggerMethod.V] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"baseSlippagePrice",b"baseSlippagePrice",u"clientOrderId",b"clientOrderId",u"closingOrder",b"closingOrder",u"executedVolume",b"executedVolume",u"executionPrice",b"executionPrice",u"expirationTimestamp",b"expirationTimestamp",u"isStopOut",b"isStopOut",u"limitPrice",b"limitPrice",u"orderId",b"orderId",u"orderStatus",b"orderStatus",u"orderType",b"orderType",u"positionId",b"positionId",u"relativeStopLoss",b"relativeStopLoss",u"relativeTakeProfit",b"relativeTakeProfit",u"slippageInPoints",b"slippageInPoints",u"stopLoss",b"stopLoss",u"stopPrice",b"stopPrice",u"stopTriggerMethod",b"stopTriggerMethod",u"takeProfit",b"takeProfit",u"timeInForce",b"timeInForce",u"tradeData",b"tradeData",u"trailingStopLoss",b"trailingStopLoss",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"baseSlippagePrice",b"baseSlippagePrice",u"clientOrderId",b"clientOrderId",u"closingOrder",b"closingOrder",u"executedVolume",b"executedVolume",u"executionPrice",b"executionPrice",u"expirationTimestamp",b"expirationTimestamp",u"isStopOut",b"isStopOut",u"limitPrice",b"limitPrice",u"orderId",b"orderId",u"orderStatus",b"orderStatus",u"orderType",b"orderType",u"positionId",b"positionId",u"relativeStopLoss",b"relativeStopLoss",u"relativeTakeProfit",b"relativeTakeProfit",u"slippageInPoints",b"slippageInPoints",u"stopLoss",b"stopLoss",u"stopPrice",b"stopPrice",u"stopTriggerMethod",b"stopTriggerMethod",u"takeProfit",b"takeProfit",u"timeInForce",b"timeInForce",u"tradeData",b"tradeData",u"trailingStopLoss",b"trailingStopLoss",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> None: ...
global___ProtoOAOrder = ProtoOAOrder

class ProtoOABonusDepositWithdraw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OPERATIONTYPE_FIELD_NUMBER: builtins.int
    BONUSHISTORYID_FIELD_NUMBER: builtins.int
    MANAGERBONUS_FIELD_NUMBER: builtins.int
    MANAGERDELTA_FIELD_NUMBER: builtins.int
    IBBONUS_FIELD_NUMBER: builtins.int
    IBDELTA_FIELD_NUMBER: builtins.int
    CHANGEBONUSTIMESTAMP_FIELD_NUMBER: builtins.int
    EXTERNALNOTE_FIELD_NUMBER: builtins.int
    INTRODUCINGBROKERID_FIELD_NUMBER: builtins.int
    MONEYDIGITS_FIELD_NUMBER: builtins.int
    operationType: global___ProtoOAChangeBonusType.V = ...
    bonusHistoryId: builtins.int = ...
    managerBonus: builtins.int = ...
    managerDelta: builtins.int = ...
    ibBonus: builtins.int = ...
    ibDelta: builtins.int = ...
    changeBonusTimestamp: builtins.int = ...
    externalNote: typing.Text = ...
    introducingBrokerId: builtins.int = ...
    moneyDigits: builtins.int = ...

    def __init__(self,
        *,
        operationType : typing.Optional[global___ProtoOAChangeBonusType.V] = ...,
        bonusHistoryId : typing.Optional[builtins.int] = ...,
        managerBonus : typing.Optional[builtins.int] = ...,
        managerDelta : typing.Optional[builtins.int] = ...,
        ibBonus : typing.Optional[builtins.int] = ...,
        ibDelta : typing.Optional[builtins.int] = ...,
        changeBonusTimestamp : typing.Optional[builtins.int] = ...,
        externalNote : typing.Optional[typing.Text] = ...,
        introducingBrokerId : typing.Optional[builtins.int] = ...,
        moneyDigits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"bonusHistoryId",b"bonusHistoryId",u"changeBonusTimestamp",b"changeBonusTimestamp",u"externalNote",b"externalNote",u"ibBonus",b"ibBonus",u"ibDelta",b"ibDelta",u"introducingBrokerId",b"introducingBrokerId",u"managerBonus",b"managerBonus",u"managerDelta",b"managerDelta",u"moneyDigits",b"moneyDigits",u"operationType",b"operationType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bonusHistoryId",b"bonusHistoryId",u"changeBonusTimestamp",b"changeBonusTimestamp",u"externalNote",b"externalNote",u"ibBonus",b"ibBonus",u"ibDelta",b"ibDelta",u"introducingBrokerId",b"introducingBrokerId",u"managerBonus",b"managerBonus",u"managerDelta",b"managerDelta",u"moneyDigits",b"moneyDigits",u"operationType",b"operationType"]) -> None: ...
global___ProtoOABonusDepositWithdraw = ProtoOABonusDepositWithdraw

class ProtoOADepositWithdraw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OPERATIONTYPE_FIELD_NUMBER: builtins.int
    BALANCEHISTORYID_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    DELTA_FIELD_NUMBER: builtins.int
    CHANGEBALANCETIMESTAMP_FIELD_NUMBER: builtins.int
    EXTERNALNOTE_FIELD_NUMBER: builtins.int
    BALANCEVERSION_FIELD_NUMBER: builtins.int
    EQUITY_FIELD_NUMBER: builtins.int
    MONEYDIGITS_FIELD_NUMBER: builtins.int
    operationType: global___ProtoOAChangeBalanceType.V = ...
    balanceHistoryId: builtins.int = ...
    balance: builtins.int = ...
    delta: builtins.int = ...
    changeBalanceTimestamp: builtins.int = ...
    externalNote: typing.Text = ...
    balanceVersion: builtins.int = ...
    equity: builtins.int = ...
    moneyDigits: builtins.int = ...

    def __init__(self,
        *,
        operationType : typing.Optional[global___ProtoOAChangeBalanceType.V] = ...,
        balanceHistoryId : typing.Optional[builtins.int] = ...,
        balance : typing.Optional[builtins.int] = ...,
        delta : typing.Optional[builtins.int] = ...,
        changeBalanceTimestamp : typing.Optional[builtins.int] = ...,
        externalNote : typing.Optional[typing.Text] = ...,
        balanceVersion : typing.Optional[builtins.int] = ...,
        equity : typing.Optional[builtins.int] = ...,
        moneyDigits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"balance",b"balance",u"balanceHistoryId",b"balanceHistoryId",u"balanceVersion",b"balanceVersion",u"changeBalanceTimestamp",b"changeBalanceTimestamp",u"delta",b"delta",u"equity",b"equity",u"externalNote",b"externalNote",u"moneyDigits",b"moneyDigits",u"operationType",b"operationType"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"balance",b"balance",u"balanceHistoryId",b"balanceHistoryId",u"balanceVersion",b"balanceVersion",u"changeBalanceTimestamp",b"changeBalanceTimestamp",u"delta",b"delta",u"equity",b"equity",u"externalNote",b"externalNote",u"moneyDigits",b"moneyDigits",u"operationType",b"operationType"]) -> None: ...
global___ProtoOADepositWithdraw = ProtoOADepositWithdraw

class ProtoOADeal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEALID_FIELD_NUMBER: builtins.int
    ORDERID_FIELD_NUMBER: builtins.int
    POSITIONID_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    FILLEDVOLUME_FIELD_NUMBER: builtins.int
    SYMBOLID_FIELD_NUMBER: builtins.int
    CREATETIMESTAMP_FIELD_NUMBER: builtins.int
    EXECUTIONTIMESTAMP_FIELD_NUMBER: builtins.int
    UTCLASTUPDATETIMESTAMP_FIELD_NUMBER: builtins.int
    EXECUTIONPRICE_FIELD_NUMBER: builtins.int
    TRADESIDE_FIELD_NUMBER: builtins.int
    DEALSTATUS_FIELD_NUMBER: builtins.int
    MARGINRATE_FIELD_NUMBER: builtins.int
    COMMISSION_FIELD_NUMBER: builtins.int
    BASETOUSDCONVERSIONRATE_FIELD_NUMBER: builtins.int
    CLOSEPOSITIONDETAIL_FIELD_NUMBER: builtins.int
    MONEYDIGITS_FIELD_NUMBER: builtins.int
    dealId: builtins.int = ...
    orderId: builtins.int = ...
    positionId: builtins.int = ...
    volume: builtins.int = ...
    filledVolume: builtins.int = ...
    symbolId: builtins.int = ...
    createTimestamp: builtins.int = ...
    executionTimestamp: builtins.int = ...
    utcLastUpdateTimestamp: builtins.int = ...
    executionPrice: builtins.float = ...
    tradeSide: global___ProtoOATradeSide.V = ...
    dealStatus: global___ProtoOADealStatus.V = ...
    marginRate: builtins.float = ...
    commission: builtins.int = ...
    baseToUsdConversionRate: builtins.float = ...
    moneyDigits: builtins.int = ...

    @property
    def closePositionDetail(self) -> global___ProtoOAClosePositionDetail: ...

    def __init__(self,
        *,
        dealId : typing.Optional[builtins.int] = ...,
        orderId : typing.Optional[builtins.int] = ...,
        positionId : typing.Optional[builtins.int] = ...,
        volume : typing.Optional[builtins.int] = ...,
        filledVolume : typing.Optional[builtins.int] = ...,
        symbolId : typing.Optional[builtins.int] = ...,
        createTimestamp : typing.Optional[builtins.int] = ...,
        executionTimestamp : typing.Optional[builtins.int] = ...,
        utcLastUpdateTimestamp : typing.Optional[builtins.int] = ...,
        executionPrice : typing.Optional[builtins.float] = ...,
        tradeSide : typing.Optional[global___ProtoOATradeSide.V] = ...,
        dealStatus : typing.Optional[global___ProtoOADealStatus.V] = ...,
        marginRate : typing.Optional[builtins.float] = ...,
        commission : typing.Optional[builtins.int] = ...,
        baseToUsdConversionRate : typing.Optional[builtins.float] = ...,
        closePositionDetail : typing.Optional[global___ProtoOAClosePositionDetail] = ...,
        moneyDigits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"baseToUsdConversionRate",b"baseToUsdConversionRate",u"closePositionDetail",b"closePositionDetail",u"commission",b"commission",u"createTimestamp",b"createTimestamp",u"dealId",b"dealId",u"dealStatus",b"dealStatus",u"executionPrice",b"executionPrice",u"executionTimestamp",b"executionTimestamp",u"filledVolume",b"filledVolume",u"marginRate",b"marginRate",u"moneyDigits",b"moneyDigits",u"orderId",b"orderId",u"positionId",b"positionId",u"symbolId",b"symbolId",u"tradeSide",b"tradeSide",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp",u"volume",b"volume"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"baseToUsdConversionRate",b"baseToUsdConversionRate",u"closePositionDetail",b"closePositionDetail",u"commission",b"commission",u"createTimestamp",b"createTimestamp",u"dealId",b"dealId",u"dealStatus",b"dealStatus",u"executionPrice",b"executionPrice",u"executionTimestamp",b"executionTimestamp",u"filledVolume",b"filledVolume",u"marginRate",b"marginRate",u"moneyDigits",b"moneyDigits",u"orderId",b"orderId",u"positionId",b"positionId",u"symbolId",b"symbolId",u"tradeSide",b"tradeSide",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp",u"volume",b"volume"]) -> None: ...
global___ProtoOADeal = ProtoOADeal

class ProtoOAClosePositionDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ENTRYPRICE_FIELD_NUMBER: builtins.int
    GROSSPROFIT_FIELD_NUMBER: builtins.int
    SWAP_FIELD_NUMBER: builtins.int
    COMMISSION_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    QUOTETODEPOSITCONVERSIONRATE_FIELD_NUMBER: builtins.int
    CLOSEDVOLUME_FIELD_NUMBER: builtins.int
    BALANCEVERSION_FIELD_NUMBER: builtins.int
    MONEYDIGITS_FIELD_NUMBER: builtins.int
    entryPrice: builtins.float = ...
    grossProfit: builtins.int = ...
    swap: builtins.int = ...
    commission: builtins.int = ...
    balance: builtins.int = ...
    quoteToDepositConversionRate: builtins.float = ...
    closedVolume: builtins.int = ...
    balanceVersion: builtins.int = ...
    moneyDigits: builtins.int = ...

    def __init__(self,
        *,
        entryPrice : typing.Optional[builtins.float] = ...,
        grossProfit : typing.Optional[builtins.int] = ...,
        swap : typing.Optional[builtins.int] = ...,
        commission : typing.Optional[builtins.int] = ...,
        balance : typing.Optional[builtins.int] = ...,
        quoteToDepositConversionRate : typing.Optional[builtins.float] = ...,
        closedVolume : typing.Optional[builtins.int] = ...,
        balanceVersion : typing.Optional[builtins.int] = ...,
        moneyDigits : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"balance",b"balance",u"balanceVersion",b"balanceVersion",u"closedVolume",b"closedVolume",u"commission",b"commission",u"entryPrice",b"entryPrice",u"grossProfit",b"grossProfit",u"moneyDigits",b"moneyDigits",u"quoteToDepositConversionRate",b"quoteToDepositConversionRate",u"swap",b"swap"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"balance",b"balance",u"balanceVersion",b"balanceVersion",u"closedVolume",b"closedVolume",u"commission",b"commission",u"entryPrice",b"entryPrice",u"grossProfit",b"grossProfit",u"moneyDigits",b"moneyDigits",u"quoteToDepositConversionRate",b"quoteToDepositConversionRate",u"swap",b"swap"]) -> None: ...
global___ProtoOAClosePositionDetail = ProtoOAClosePositionDetail

class ProtoOATrendbar(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VOLUME_FIELD_NUMBER: builtins.int
    PERIOD_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    DELTAOPEN_FIELD_NUMBER: builtins.int
    DELTACLOSE_FIELD_NUMBER: builtins.int
    DELTAHIGH_FIELD_NUMBER: builtins.int
    UTCTIMESTAMPINMINUTES_FIELD_NUMBER: builtins.int
    volume: builtins.int = ...
    period: global___ProtoOATrendbarPeriod.V = ...
    low: builtins.int = ...
    deltaOpen: builtins.int = ...
    deltaClose: builtins.int = ...
    deltaHigh: builtins.int = ...
    utcTimestampInMinutes: builtins.int = ...

    def __init__(self,
        *,
        volume : typing.Optional[builtins.int] = ...,
        period : typing.Optional[global___ProtoOATrendbarPeriod.V] = ...,
        low : typing.Optional[builtins.int] = ...,
        deltaOpen : typing.Optional[builtins.int] = ...,
        deltaClose : typing.Optional[builtins.int] = ...,
        deltaHigh : typing.Optional[builtins.int] = ...,
        utcTimestampInMinutes : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"deltaClose",b"deltaClose",u"deltaHigh",b"deltaHigh",u"deltaOpen",b"deltaOpen",u"low",b"low",u"period",b"period",u"utcTimestampInMinutes",b"utcTimestampInMinutes",u"volume",b"volume"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"deltaClose",b"deltaClose",u"deltaHigh",b"deltaHigh",u"deltaOpen",b"deltaOpen",u"low",b"low",u"period",b"period",u"utcTimestampInMinutes",b"utcTimestampInMinutes",u"volume",b"volume"]) -> None: ...
global___ProtoOATrendbar = ProtoOATrendbar

class ProtoOAExpectedMargin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VOLUME_FIELD_NUMBER: builtins.int
    BUYMARGIN_FIELD_NUMBER: builtins.int
    SELLMARGIN_FIELD_NUMBER: builtins.int
    volume: builtins.int = ...
    buyMargin: builtins.int = ...
    sellMargin: builtins.int = ...

    def __init__(self,
        *,
        volume : typing.Optional[builtins.int] = ...,
        buyMargin : typing.Optional[builtins.int] = ...,
        sellMargin : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"buyMargin",b"buyMargin",u"sellMargin",b"sellMargin",u"volume",b"volume"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"buyMargin",b"buyMargin",u"sellMargin",b"sellMargin",u"volume",b"volume"]) -> None: ...
global___ProtoOAExpectedMargin = ProtoOAExpectedMargin

class ProtoOATickData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIMESTAMP_FIELD_NUMBER: builtins.int
    TICK_FIELD_NUMBER: builtins.int
    timestamp: builtins.int = ...
    tick: builtins.int = ...

    def __init__(self,
        *,
        timestamp : typing.Optional[builtins.int] = ...,
        tick : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"tick",b"tick",u"timestamp",b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"tick",b"tick",u"timestamp",b"timestamp"]) -> None: ...
global___ProtoOATickData = ProtoOATickData

class ProtoOACtidProfile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    USERID_FIELD_NUMBER: builtins.int
    userId: builtins.int = ...

    def __init__(self,
        *,
        userId : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"userId",b"userId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"userId",b"userId"]) -> None: ...
global___ProtoOACtidProfile = ProtoOACtidProfile

class ProtoOACtidTraderAccount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CTIDTRADERACCOUNTID_FIELD_NUMBER: builtins.int
    ISLIVE_FIELD_NUMBER: builtins.int
    TRADERLOGIN_FIELD_NUMBER: builtins.int
    LASTCLOSINGDEALTIMESTAMP_FIELD_NUMBER: builtins.int
    LASTBALANCEUPDATETIMESTAMP_FIELD_NUMBER: builtins.int
    ctidTraderAccountId: builtins.int = ...
    isLive: builtins.bool = ...
    traderLogin: builtins.int = ...
    lastClosingDealTimestamp: builtins.int = ...
    lastBalanceUpdateTimestamp: builtins.int = ...

    def __init__(self,
        *,
        ctidTraderAccountId : typing.Optional[builtins.int] = ...,
        isLive : typing.Optional[builtins.bool] = ...,
        traderLogin : typing.Optional[builtins.int] = ...,
        lastClosingDealTimestamp : typing.Optional[builtins.int] = ...,
        lastBalanceUpdateTimestamp : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ctidTraderAccountId",b"ctidTraderAccountId",u"isLive",b"isLive",u"lastBalanceUpdateTimestamp",b"lastBalanceUpdateTimestamp",u"lastClosingDealTimestamp",b"lastClosingDealTimestamp",u"traderLogin",b"traderLogin"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ctidTraderAccountId",b"ctidTraderAccountId",u"isLive",b"isLive",u"lastBalanceUpdateTimestamp",b"lastBalanceUpdateTimestamp",u"lastClosingDealTimestamp",b"lastClosingDealTimestamp",u"traderLogin",b"traderLogin"]) -> None: ...
global___ProtoOACtidTraderAccount = ProtoOACtidTraderAccount

class ProtoOAAssetClass(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.int = ...
    name: typing.Text = ...

    def __init__(self,
        *,
        id : typing.Optional[builtins.int] = ...,
        name : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"id",b"id",u"name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id",u"name",b"name"]) -> None: ...
global___ProtoOAAssetClass = ProtoOAAssetClass

class ProtoOADepthQuote(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    BID_FIELD_NUMBER: builtins.int
    ASK_FIELD_NUMBER: builtins.int
    id: builtins.int = ...
    size: builtins.int = ...
    bid: builtins.int = ...
    ask: builtins.int = ...

    def __init__(self,
        *,
        id : typing.Optional[builtins.int] = ...,
        size : typing.Optional[builtins.int] = ...,
        bid : typing.Optional[builtins.int] = ...,
        ask : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ask",b"ask",u"bid",b"bid",u"id",b"id",u"size",b"size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ask",b"ask",u"bid",b"bid",u"id",b"id",u"size",b"size"]) -> None: ...
global___ProtoOADepthQuote = ProtoOADepthQuote

class ProtoOAMarginCall(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MARGINCALLTYPE_FIELD_NUMBER: builtins.int
    MARGINLEVELTHRESHOLD_FIELD_NUMBER: builtins.int
    UTCLASTUPDATETIMESTAMP_FIELD_NUMBER: builtins.int
    marginCallType: global___ProtoOANotificationType.V = ...
    marginLevelThreshold: builtins.float = ...
    utcLastUpdateTimestamp: builtins.int = ...

    def __init__(self,
        *,
        marginCallType : typing.Optional[global___ProtoOANotificationType.V] = ...,
        marginLevelThreshold : typing.Optional[builtins.float] = ...,
        utcLastUpdateTimestamp : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"marginCallType",b"marginCallType",u"marginLevelThreshold",b"marginLevelThreshold",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"marginCallType",b"marginCallType",u"marginLevelThreshold",b"marginLevelThreshold",u"utcLastUpdateTimestamp",b"utcLastUpdateTimestamp"]) -> None: ...
global___ProtoOAMarginCall = ProtoOAMarginCall

class ProtoOAHoliday(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HOLIDAYID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    SCHEDULETIMEZONE_FIELD_NUMBER: builtins.int
    HOLIDAYDATE_FIELD_NUMBER: builtins.int
    ISRECURRING_FIELD_NUMBER: builtins.int
    STARTSECOND_FIELD_NUMBER: builtins.int
    ENDSECOND_FIELD_NUMBER: builtins.int
    holidayId: builtins.int = ...
    name: typing.Text = ...
    description: typing.Text = ...
    scheduleTimeZone: typing.Text = ...
    holidayDate: builtins.int = ...
    isRecurring: builtins.bool = ...
    startSecond: builtins.int = ...
    endSecond: builtins.int = ...

    def __init__(self,
        *,
        holidayId : typing.Optional[builtins.int] = ...,
        name : typing.Optional[typing.Text] = ...,
        description : typing.Optional[typing.Text] = ...,
        scheduleTimeZone : typing.Optional[typing.Text] = ...,
        holidayDate : typing.Optional[builtins.int] = ...,
        isRecurring : typing.Optional[builtins.bool] = ...,
        startSecond : typing.Optional[builtins.int] = ...,
        endSecond : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"description",b"description",u"endSecond",b"endSecond",u"holidayDate",b"holidayDate",u"holidayId",b"holidayId",u"isRecurring",b"isRecurring",u"name",b"name",u"scheduleTimeZone",b"scheduleTimeZone",u"startSecond",b"startSecond"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"description",b"description",u"endSecond",b"endSecond",u"holidayDate",b"holidayDate",u"holidayId",b"holidayId",u"isRecurring",b"isRecurring",u"name",b"name",u"scheduleTimeZone",b"scheduleTimeZone",u"startSecond",b"startSecond"]) -> None: ...
global___ProtoOAHoliday = ProtoOAHoliday
